version: '3.8'
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DOCKER_HOST=unix:///run/docker.sock
    volumes:
      - ./:/root
      - /run/docker.sock:/run/docker.sock:ro
    working_dir: /root
    command: sh /root/get_name.sh

